# Écran de verrouillage (Super + L).

background {
    monitor =
    color = rgba(1e1e2eff)
    blur_passes = 2
    blur_size = 7
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_center = true
    outer_color = rgba(89b4faff)
    inner_color = rgba(313244ff)
    font_color = rgba(cdd6f4ff)
    fail_color = rgba(f38ba8ff)
    placeholder_text = <i>Mot de passe…</i>
    fail_text = <i>Échec ($ATTEMPTS)</i>
    position = 0, -50
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgba(cdd6f4ff)
    font_size = 64
    font_family = JetBrains Mono
    position = 0, 120
    halign = center
    valign = center
}
